# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_vfctjt5J_i5NRzFSSM67gCkMnHyYUmh
"""

def consulta():
    nome = input("Digite aqui o nome do paciente: ")
    cpf_paciente = int(input("Digite aqui o CPF do paciente: "))
    endereco_paciente = input("Digite aqui o endereço do paciente: ")
    print("O nome do paciente atual é: ",nome, "inscrito no CPF de numero: ", cpf_paciente, "residente no endereço: ", endereco_paciente, ". Engenheiro Beltrão| Parana." )

def produto():
    num1 = float(input("Digite o Valor do Produto : "))
    num2 = int(input("Digite a Quantidade : "))

    print("O valor da compra é : ", num1, "*", num2, "é igual : ", num1 * num2)




menu = int(input('''----------
      O que voce deseja fazer Julio:
      1-soma
      2-Divisão
      3-Multiplicação

      '''))
if menu == 1:
    print("Voce escolheu a opção somar: ")

    consulta()
    produto()